// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/session.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 762856598;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'kolibri_dart',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<HandshakeInfo> crateApiSessionKolibriSessionConnect(
      {required KolibriSession that});

  void crateApiSessionKolibriSessionDisconnect({required KolibriSession that});

  KolibriSession crateApiSessionKolibriSessionNew(
      {required SessionOptions options});

  Stream<PushEvent> crateApiSessionKolibriSessionPushes(
      {required KolibriSession that});

  Future<Uint8List> crateApiSessionKolibriSessionRequest(
      {required KolibriSession that,
      required int opcode,
      required List<int> payload});

  int crateApiSessionKolibriSessionSend(
      {required KolibriSession that,
      required int opcode,
      required List<int> payload});

  String crateApiSessionKolibriSessionState({required KolibriSession that});

  Stream<UploadEvent> crateApiSessionKolibriSessionUploadFile(
      {required KolibriSession that,
      required String url,
      required List<int> data,
      required String filename});

  Stream<UploadEvent> crateApiSessionKolibriSessionUploadPhoto(
      {required KolibriSession that,
      required String url,
      required List<int> data,
      required String filename});

  Stream<UploadEvent> crateApiSessionKolibriSessionUploadVideo(
      {required KolibriSession that,
      required String url,
      required List<int> data,
      required int chunkSize,
      required int concurrency});

  Uint8List crateApiSessionAuthMode(
      {required List<int> signature,
      required List<int> dex,
      required List<int> so,
      required PlatformInt64 callsSeed,
      required String deviceId});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_KolibriSession;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_KolibriSession;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_KolibriSessionPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<HandshakeInfo> crateApiSessionKolibriSessionConnect(
      {required KolibriSession that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_handshake_info,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSessionKolibriSessionConnectConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionKolibriSessionConnectConstMeta =>
      const TaskConstMeta(
        debugName: "KolibriSession_connect",
        argNames: ["that"],
      );

  @override
  void crateApiSessionKolibriSessionDisconnect({required KolibriSession that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSessionKolibriSessionDisconnectConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionKolibriSessionDisconnectConstMeta =>
      const TaskConstMeta(
        debugName: "KolibriSession_disconnect",
        argNames: ["that"],
      );

  @override
  KolibriSession crateApiSessionKolibriSessionNew(
      {required SessionOptions options}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_session_options(options, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSessionKolibriSessionNewConstMeta,
      argValues: [options],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionKolibriSessionNewConstMeta =>
      const TaskConstMeta(
        debugName: "KolibriSession_new",
        argNames: ["options"],
      );

  @override
  Stream<PushEvent> crateApiSessionKolibriSessionPushes(
      {required KolibriSession that}) {
    final sink = RustStreamSink<PushEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
            that, serializer);
        sse_encode_StreamSink_push_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSessionKolibriSessionPushesConstMeta,
      argValues: [that, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSessionKolibriSessionPushesConstMeta =>
      const TaskConstMeta(
        debugName: "KolibriSession_pushes",
        argNames: ["that", "sink"],
      );

  @override
  Future<Uint8List> crateApiSessionKolibriSessionRequest(
      {required KolibriSession that,
      required int opcode,
      required List<int> payload}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
            that, serializer);
        sse_encode_u_16(opcode, serializer);
        sse_encode_list_prim_u_8_loose(payload, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSessionKolibriSessionRequestConstMeta,
      argValues: [that, opcode, payload],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionKolibriSessionRequestConstMeta =>
      const TaskConstMeta(
        debugName: "KolibriSession_request",
        argNames: ["that", "opcode", "payload"],
      );

  @override
  int crateApiSessionKolibriSessionSend(
      {required KolibriSession that,
      required int opcode,
      required List<int> payload}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
            that, serializer);
        sse_encode_u_16(opcode, serializer);
        sse_encode_list_prim_u_8_loose(payload, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSessionKolibriSessionSendConstMeta,
      argValues: [that, opcode, payload],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionKolibriSessionSendConstMeta =>
      const TaskConstMeta(
        debugName: "KolibriSession_send",
        argNames: ["that", "opcode", "payload"],
      );

  @override
  String crateApiSessionKolibriSessionState({required KolibriSession that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSessionKolibriSessionStateConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionKolibriSessionStateConstMeta =>
      const TaskConstMeta(
        debugName: "KolibriSession_state",
        argNames: ["that"],
      );

  @override
  Stream<UploadEvent> crateApiSessionKolibriSessionUploadFile(
      {required KolibriSession that,
      required String url,
      required List<int> data,
      required String filename}) {
    final sink = RustStreamSink<UploadEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
            that, serializer);
        sse_encode_String(url, serializer);
        sse_encode_list_prim_u_8_loose(data, serializer);
        sse_encode_String(filename, serializer);
        sse_encode_StreamSink_upload_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSessionKolibriSessionUploadFileConstMeta,
      argValues: [that, url, data, filename, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSessionKolibriSessionUploadFileConstMeta =>
      const TaskConstMeta(
        debugName: "KolibriSession_upload_file",
        argNames: ["that", "url", "data", "filename", "sink"],
      );

  @override
  Stream<UploadEvent> crateApiSessionKolibriSessionUploadPhoto(
      {required KolibriSession that,
      required String url,
      required List<int> data,
      required String filename}) {
    final sink = RustStreamSink<UploadEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
            that, serializer);
        sse_encode_String(url, serializer);
        sse_encode_list_prim_u_8_loose(data, serializer);
        sse_encode_String(filename, serializer);
        sse_encode_StreamSink_upload_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSessionKolibriSessionUploadPhotoConstMeta,
      argValues: [that, url, data, filename, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSessionKolibriSessionUploadPhotoConstMeta =>
      const TaskConstMeta(
        debugName: "KolibriSession_upload_photo",
        argNames: ["that", "url", "data", "filename", "sink"],
      );

  @override
  Stream<UploadEvent> crateApiSessionKolibriSessionUploadVideo(
      {required KolibriSession that,
      required String url,
      required List<int> data,
      required int chunkSize,
      required int concurrency}) {
    final sink = RustStreamSink<UploadEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
            that, serializer);
        sse_encode_String(url, serializer);
        sse_encode_list_prim_u_8_loose(data, serializer);
        sse_encode_u_32(chunkSize, serializer);
        sse_encode_u_32(concurrency, serializer);
        sse_encode_StreamSink_upload_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSessionKolibriSessionUploadVideoConstMeta,
      argValues: [that, url, data, chunkSize, concurrency, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSessionKolibriSessionUploadVideoConstMeta =>
      const TaskConstMeta(
        debugName: "KolibriSession_upload_video",
        argNames: ["that", "url", "data", "chunkSize", "concurrency", "sink"],
      );

  @override
  Uint8List crateApiSessionAuthMode(
      {required List<int> signature,
      required List<int> dex,
      required List<int> so,
      required PlatformInt64 callsSeed,
      required String deviceId}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(signature, serializer);
        sse_encode_list_prim_u_8_loose(dex, serializer);
        sse_encode_list_prim_u_8_loose(so, serializer);
        sse_encode_i_64(callsSeed, serializer);
        sse_encode_String(deviceId, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSessionAuthModeConstMeta,
      argValues: [signature, dex, so, callsSeed, deviceId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionAuthModeConstMeta => const TaskConstMeta(
        debugName: "auth_mode",
        argNames: ["signature", "dex", "so", "callsSeed", "deviceId"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_KolibriSession => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_KolibriSession => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  KolibriSession
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KolibriSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  KolibriSession
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KolibriSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  KolibriSession
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KolibriSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<PushEvent> dco_decode_StreamSink_push_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<UploadEvent> dco_decode_StreamSink_upload_event_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  SessionOptions dco_decode_box_autoadd_session_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_session_options(raw);
  }

  @protected
  HandshakeInfo dco_decode_handshake_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HandshakeInfo(
      callsSeed: dco_decode_opt_box_autoadd_i_64(arr[0]),
      deviceName: dco_decode_opt_String(arr[1]),
      payload: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  PushEvent dco_decode_push_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PushEvent(
      opcode: dco_decode_u_16(arr[0]),
      payload: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  SessionOptions dco_decode_session_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 19)
      throw Exception('unexpected arr length: expect 19 but see ${arr.length}');
    return SessionOptions(
      host: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
      deviceId: dco_decode_String(arr[2]),
      instanceId: dco_decode_String(arr[3]),
      appVersion: dco_decode_String(arr[4]),
      buildNumber: dco_decode_i_64(arr[5]),
      deviceType: dco_decode_String(arr[6]),
      osVersion: dco_decode_String(arr[7]),
      timezone: dco_decode_String(arr[8]),
      screen: dco_decode_String(arr[9]),
      pushDeviceType: dco_decode_String(arr[10]),
      arch: dco_decode_String(arr[11]),
      locale: dco_decode_String(arr[12]),
      deviceName: dco_decode_String(arr[13]),
      deviceLocale: dco_decode_String(arr[14]),
      clientSessionId: dco_decode_i_64(arr[15]),
      pingIntervalSecs: dco_decode_u_64(arr[16]),
      autoReconnect: dco_decode_bool(arr[17]),
      insecureTls: dco_decode_bool(arr[18]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UploadEvent dco_decode_upload_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return UploadEvent_Progress(
          sent: dco_decode_u_64(raw[1]),
          total: dco_decode_u_64(raw[2]),
        );
      case 1:
        return UploadEvent_Done(
          status: dco_decode_u_16(raw[1]),
          body: dco_decode_list_prim_u_8_strict(raw[2]),
        );
      case 2:
        return UploadEvent_Error(
          message: dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  KolibriSession
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KolibriSessionImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  KolibriSession
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KolibriSessionImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  KolibriSession
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KolibriSessionImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustStreamSink<PushEvent> sse_decode_StreamSink_push_event_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<UploadEvent> sse_decode_StreamSink_upload_event_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  SessionOptions sse_decode_box_autoadd_session_options(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_session_options(deserializer));
  }

  @protected
  HandshakeInfo sse_decode_handshake_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_callsSeed = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_deviceName = sse_decode_opt_String(deserializer);
    var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
    return HandshakeInfo(
        callsSeed: var_callsSeed,
        deviceName: var_deviceName,
        payload: var_payload);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PushEvent sse_decode_push_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_opcode = sse_decode_u_16(deserializer);
    var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
    return PushEvent(opcode: var_opcode, payload: var_payload);
  }

  @protected
  SessionOptions sse_decode_session_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_instanceId = sse_decode_String(deserializer);
    var var_appVersion = sse_decode_String(deserializer);
    var var_buildNumber = sse_decode_i_64(deserializer);
    var var_deviceType = sse_decode_String(deserializer);
    var var_osVersion = sse_decode_String(deserializer);
    var var_timezone = sse_decode_String(deserializer);
    var var_screen = sse_decode_String(deserializer);
    var var_pushDeviceType = sse_decode_String(deserializer);
    var var_arch = sse_decode_String(deserializer);
    var var_locale = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_deviceLocale = sse_decode_String(deserializer);
    var var_clientSessionId = sse_decode_i_64(deserializer);
    var var_pingIntervalSecs = sse_decode_u_64(deserializer);
    var var_autoReconnect = sse_decode_bool(deserializer);
    var var_insecureTls = sse_decode_bool(deserializer);
    return SessionOptions(
        host: var_host,
        port: var_port,
        deviceId: var_deviceId,
        instanceId: var_instanceId,
        appVersion: var_appVersion,
        buildNumber: var_buildNumber,
        deviceType: var_deviceType,
        osVersion: var_osVersion,
        timezone: var_timezone,
        screen: var_screen,
        pushDeviceType: var_pushDeviceType,
        arch: var_arch,
        locale: var_locale,
        deviceName: var_deviceName,
        deviceLocale: var_deviceLocale,
        clientSessionId: var_clientSessionId,
        pingIntervalSecs: var_pingIntervalSecs,
        autoReconnect: var_autoReconnect,
        insecureTls: var_insecureTls);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UploadEvent sse_decode_upload_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_sent = sse_decode_u_64(deserializer);
        var var_total = sse_decode_u_64(deserializer);
        return UploadEvent_Progress(sent: var_sent, total: var_total);
      case 1:
        var var_status = sse_decode_u_16(deserializer);
        var var_body = sse_decode_list_prim_u_8_strict(deserializer);
        return UploadEvent_Done(status: var_status, body: var_body);
      case 2:
        var var_message = sse_decode_String(deserializer);
        return UploadEvent_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
          KolibriSession self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as KolibriSessionImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
          KolibriSession self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as KolibriSessionImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKolibriSession(
          KolibriSession self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as KolibriSessionImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_push_event_Sse(
      RustStreamSink<PushEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_push_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_upload_event_Sse(
      RustStreamSink<UploadEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_upload_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_session_options(
      SessionOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_session_options(self, serializer);
  }

  @protected
  void sse_encode_handshake_info(HandshakeInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.callsSeed, serializer);
    sse_encode_opt_String(self.deviceName, serializer);
    sse_encode_list_prim_u_8_strict(self.payload, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_push_event(PushEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.opcode, serializer);
    sse_encode_list_prim_u_8_strict(self.payload, serializer);
  }

  @protected
  void sse_encode_session_options(
      SessionOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.instanceId, serializer);
    sse_encode_String(self.appVersion, serializer);
    sse_encode_i_64(self.buildNumber, serializer);
    sse_encode_String(self.deviceType, serializer);
    sse_encode_String(self.osVersion, serializer);
    sse_encode_String(self.timezone, serializer);
    sse_encode_String(self.screen, serializer);
    sse_encode_String(self.pushDeviceType, serializer);
    sse_encode_String(self.arch, serializer);
    sse_encode_String(self.locale, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.deviceLocale, serializer);
    sse_encode_i_64(self.clientSessionId, serializer);
    sse_encode_u_64(self.pingIntervalSecs, serializer);
    sse_encode_bool(self.autoReconnect, serializer);
    sse_encode_bool(self.insecureTls, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_upload_event(UploadEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case UploadEvent_Progress(sent: final sent, total: final total):
        sse_encode_i_32(0, serializer);
        sse_encode_u_64(sent, serializer);
        sse_encode_u_64(total, serializer);
      case UploadEvent_Done(status: final status, body: final body):
        sse_encode_i_32(1, serializer);
        sse_encode_u_16(status, serializer);
        sse_encode_list_prim_u_8_strict(body, serializer);
      case UploadEvent_Error(message: final message):
        sse_encode_i_32(2, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class KolibriSessionImpl extends RustOpaque implements KolibriSession {
  // Not to be used by end users
  KolibriSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  KolibriSessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_KolibriSession,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_KolibriSession,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_KolibriSessionPtr,
  );

  /// Connect and perform the sessionInit handshake.
  Future<HandshakeInfo> connect() =>
      RustLib.instance.api.crateApiSessionKolibriSessionConnect(
        that: this,
      );

  void disconnect() =>
      RustLib.instance.api.crateApiSessionKolibriSessionDisconnect(
        that: this,
      );

  /// Stream of server pushes. Yields until the session is dropped.
  Stream<PushEvent> pushes() =>
      RustLib.instance.api.crateApiSessionKolibriSessionPushes(
        that: this,
      );

  /// Send a request and await the response payload (raw MessagePack). Errors on
  /// a server error packet or timeout.
  Future<Uint8List> request(
          {required int opcode, required List<int> payload}) =>
      RustLib.instance.api.crateApiSessionKolibriSessionRequest(
          that: this, opcode: opcode, payload: payload);

  /// Fire-and-forget send; returns the sequence number.
  int send({required int opcode, required List<int> payload}) =>
      RustLib.instance.api.crateApiSessionKolibriSessionSend(
          that: this, opcode: opcode, payload: payload);

  String state() => RustLib.instance.api.crateApiSessionKolibriSessionState(
        that: this,
      );

  /// Upload a generic file to a CDN URL. Returns a stream of [`UploadEvent`]s
  /// (progress, then Done/Error).
  Stream<UploadEvent> uploadFile(
          {required String url,
          required List<int> data,
          required String filename}) =>
      RustLib.instance.api.crateApiSessionKolibriSessionUploadFile(
          that: this, url: url, data: data, filename: filename);

  /// Upload a photo via multipart/form-data. Returns a stream of upload events;
  /// parse the `photoToken` from the `Done` body.
  Stream<UploadEvent> uploadPhoto(
          {required String url,
          required List<int> data,
          required String filename}) =>
      RustLib.instance.api.crateApiSessionKolibriSessionUploadPhoto(
          that: this, url: url, data: data, filename: filename);

  /// Upload a video in parallel resumable chunks. Returns a stream of events;
  /// `Done{status:200}` means success.
  Stream<UploadEvent> uploadVideo(
          {required String url,
          required List<int> data,
          required int chunkSize,
          required int concurrency}) =>
      RustLib.instance.api.crateApiSessionKolibriSessionUploadVideo(
          that: this,
          url: url,
          data: data,
          chunkSize: chunkSize,
          concurrency: concurrency);
}
