// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'session.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `drive_upload`

/// 96-byte anti-spoof fingerprint (authRequest `mode` / login `chatCacheFingerprint`).
/// signature/dex/so are raw digest bytes, passed in so they can change per app version.
Uint8List authMode(
        {required List<int> signature,
        required List<int> dex,
        required List<int> so,
        required PlatformInt64 callsSeed,
        required String deviceId}) =>
    RustLib.instance.api.crateApiSessionAuthMode(
        signature: signature,
        dex: dex,
        so: so,
        callsSeed: callsSeed,
        deviceId: deviceId);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KolibriSession>>
abstract class KolibriSession implements RustOpaqueInterface {
  /// Connect and run the sessionInit handshake.
  Future<HandshakeInfo> connect();

  void disconnect();

  factory KolibriSession({required SessionOptions options}) =>
      RustLib.instance.api.crateApiSessionKolibriSessionNew(options: options);

  /// Server pushes; yields until the session is dropped.
  Stream<PushEvent> pushes();

  /// Send a request, await the response payload (raw msgpack). Errors on server error or timeout.
  Future<Uint8List> request({required int opcode, required List<int> payload});

  /// Fire-and-forget send; returns the seq number.
  int send({required int opcode, required List<int> payload});

  String state();

  /// Upload a generic file to a CDN URL. Streams progress, then Done/Error.
  /// `user_agent` defaults to the app string when null.
  Stream<UploadEvent> uploadFile(
      {required String url,
      required List<int> data,
      required String filename,
      String? userAgent});

  /// Upload a photo via multipart/form-data. Parse `photoToken` from the `Done` body.
  Stream<UploadEvent> uploadPhoto(
      {required String url,
      required List<int> data,
      required String filename,
      String? userAgent});

  /// Upload a video in parallel resumable chunks. `Done{status:200}` means success.
  Stream<UploadEvent> uploadVideo(
      {required String url,
      required List<int> data,
      required int chunkSize,
      required int concurrency});
}

/// sessionInit handshake result. `payload` is raw MessagePack; decode it Dart-side.
class HandshakeInfo {
  final PlatformInt64? callsSeed;
  final String? deviceName;
  final Uint8List payload;

  const HandshakeInfo({
    this.callsSeed,
    this.deviceName,
    required this.payload,
  });

  @override
  int get hashCode =>
      callsSeed.hashCode ^ deviceName.hashCode ^ payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandshakeInfo &&
          runtimeType == other.runtimeType &&
          callsSeed == other.callsSeed &&
          deviceName == other.deviceName &&
          payload == other.payload;
}

/// Server push; `payload` is raw MessagePack.
class PushEvent {
  final int opcode;
  final Uint8List payload;

  const PushEvent({
    required this.opcode,
    required this.payload,
  });

  @override
  int get hashCode => opcode.hashCode ^ payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PushEvent &&
          runtimeType == other.runtimeType &&
          opcode == other.opcode &&
          payload == other.payload;
}

/// Device + connection options. Device fields feed the sessionInit handshake.
class SessionOptions {
  final String host;
  final int port;
  final String deviceId;
  final String instanceId;
  final String appVersion;
  final PlatformInt64 buildNumber;
  final String deviceType;
  final String osVersion;
  final String timezone;
  final String screen;
  final String pushDeviceType;
  final String arch;
  final String locale;
  final String deviceName;
  final String deviceLocale;
  final PlatformInt64 clientSessionId;
  final BigInt pingIntervalSecs;
  final bool autoReconnect;
  final bool insecureTls;

  const SessionOptions({
    required this.host,
    required this.port,
    required this.deviceId,
    required this.instanceId,
    required this.appVersion,
    required this.buildNumber,
    required this.deviceType,
    required this.osVersion,
    required this.timezone,
    required this.screen,
    required this.pushDeviceType,
    required this.arch,
    required this.locale,
    required this.deviceName,
    required this.deviceLocale,
    required this.clientSessionId,
    required this.pingIntervalSecs,
    required this.autoReconnect,
    required this.insecureTls,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      deviceId.hashCode ^
      instanceId.hashCode ^
      appVersion.hashCode ^
      buildNumber.hashCode ^
      deviceType.hashCode ^
      osVersion.hashCode ^
      timezone.hashCode ^
      screen.hashCode ^
      pushDeviceType.hashCode ^
      arch.hashCode ^
      locale.hashCode ^
      deviceName.hashCode ^
      deviceLocale.hashCode ^
      clientSessionId.hashCode ^
      pingIntervalSecs.hashCode ^
      autoReconnect.hashCode ^
      insecureTls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionOptions &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          deviceId == other.deviceId &&
          instanceId == other.instanceId &&
          appVersion == other.appVersion &&
          buildNumber == other.buildNumber &&
          deviceType == other.deviceType &&
          osVersion == other.osVersion &&
          timezone == other.timezone &&
          screen == other.screen &&
          pushDeviceType == other.pushDeviceType &&
          arch == other.arch &&
          locale == other.locale &&
          deviceName == other.deviceName &&
          deviceLocale == other.deviceLocale &&
          clientSessionId == other.clientSessionId &&
          pingIntervalSecs == other.pingIntervalSecs &&
          autoReconnect == other.autoReconnect &&
          insecureTls == other.insecureTls;
}

@freezed
sealed class UploadEvent with _$UploadEvent {
  const UploadEvent._();

  const factory UploadEvent.progress({
    required BigInt sent,
    required BigInt total,
  }) = UploadEvent_Progress;
  const factory UploadEvent.done({
    required int status,
    required Uint8List body,
  }) = UploadEvent_Done;
  const factory UploadEvent.error({
    required String message,
  }) = UploadEvent_Error;
}
